@ECHO OFF

SET COUNTER=0
IF NOT "%1"=="" SET COUNTER=%1
SET /A MAX=COUNTER+5
IF NOT "%2"=="" SET /A MAX=COUNTER+%2

SET BINDIR=%~dp0
cd %BINDIR%

:loop
START /B %BINDIR%editOwnerUser.bat %COUNTER%
set /A COUNTER=COUNTER+1
if %COUNTER%==%MAX% GOTO end
GOTO loop

:end
EXIT /B %ERRORLEVEL%
